FROM node:18-alpine

# Instalar git
RUN apk add --no-cache git

WORKDIR /app

# Copiar primero los archivos del backend
COPY package*.json ./
RUN npm install
COPY . .

# Clonar directamente el repositorio de los contratos en la ruta exacta que busca tu código
RUN git clone https://github.com/mangelbarrera22/glaze-blockchain.git ../glaze-contracts

EXPOSE 3000
CMD ["node", "server.js"]